from PyQt5 import QtCore, QtGui, QtWidgets
from utility import Plotter

"""В этом файле хранятся классы интерфейсов, созданных в QtDesigner"""


class Ui_SolveViewer:
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 389)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.mathModel = QtWidgets.QLabel(self.centralwidget)
        self.mathModel.setText("")
        self.mathModel.setAlignment(QtCore.Qt.AlignCenter)
        self.mathModel.setObjectName("label_2")
        self.verticalLayout.addWidget(self.mathModel)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.answer = QtWidgets.QLabel(self.centralwidget)
        self.answer.setText("")
        self.answer.setAlignment(QtCore.Qt.AlignCenter)
        self.answer.setObjectName("label_4")
        self.verticalLayout.addWidget(self.answer)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.plotter = Plotter(self.centralwidget)
        self.plotter.setObjectName("plot")
        self.horizontalLayout.addWidget(self.plotter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_4)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Решение задачи"))
        self.label.setText(_translate("MainWindow", "Математическая модель:"))
        self.label_3.setText(_translate("MainWindow", "Ответ:"))
        self.menuSettings.setTitle(_translate("MainWindow", "Настройки"))
        self.menu.setTitle(_translate("MainWindow", "Сохранить"))
        self.action.setText(_translate("MainWindow", "Сохранить в базу примеров"))
        self.action_2.setText(_translate("MainWindow", "Сохранить в отдельный файл"))
        self.action_3.setText(_translate("MainWindow", "Добавить к существующему файлу"))
        self.action_4.setText(_translate("MainWindow", "Сохранить отчёт в виде изображения"))
